dataset_source:
  type: "file"
  location: "TG-SPDCL_consumption_detail_industrial_04_2025.csv"

scope:
  filters: {}

llm:
  llm:
  model: "gemini-1.5-flash"

  temperature: 0.7

export_formats: ["ascii", "csv", "markdown", "png"]
